### ISSUE TITLE
cannot longer build in debug mode

### ISSUE THREAD

**Issue by ferdymercury** [martukas/nuclei#20]
After the latest additions to master, the build fails if CMAKE_BUILD_TYPE is set to Debug instead of Release.

It does not properly find the 'include' directories of Conan for spdlog, date, qtcolorwidgets, fmt, nlohmann, etc. And the linker does not find -lQtColorWidgets.

@php1ic do you think the ConanConfig.cmake could be modified so that it automatically sets the corresponding profile in debug mode?

See e.g. https://stackoverflow.com/questions/76501151/conan-installed-googletest-undefined-refence-in-debug-mode and 
https://github.com/conan-io/conan/issues/11175
https://github.com/conan-io/conan/issues/12656

**Comment by php1ic** [comment]
Started working on this with PR #21

**Comment by php1ic** [comment]
CI is now successfully building Debug and Release configs.

@ferdymercury can you please check if this is working for you?

**Comment by ferdymercury** [comment]
Fixed by https://github.com/martukas/nuclei/pull/21 thanks!!
