### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by ferdymercury** [martukas/nuclei#8]
When clicking C12 adopted gamma levels, nuclei crashes:

```
QGraphicsItemGroup::addToGroup: cannot add null item
QObject::connect: Cannot connect SchemeGraphics::enabledShadow(bool) to (nullptr)::setShadowEnabled(bool)
QObject::connect: Cannot connect (nullptr)::clicked(ClickableItem*) to SchemeGraphics::itemClicked(ClickableItem*)
Segmentation fault (core dumped)
```

It happens here, click_area is zero:
```
void TransitionItem::updateArrow(double arrowDestY, double max_intensity)
{
  item->removeFromGroup(click_area_);
```

**Comment by ferdymercury** [comment]
When run via QtCreator and gcc11, I see many compilation warnings, and then a crash:

```
Starting /home/user/build/build-nuclei-Desktop-Debug/bin/nuclei...
terminate called after throwing an instance of 'spdlog::spdlog_ex'
  what():  Failed opening file nuclei for writing: Text file busy
```

if I set `if(!logfilename.empty() && false)` I skip the crash

**Comment by martukas** [comment]
Does this also happen in CI? We should probably pick a particular distribution (latest ubuntu LTS?), one compiler (whichever is standard in that distro?), same for most libraries if possible, and just make sure it works with that?

**Comment by ferdymercury** [comment]
Agreed! (I used Ubuntu22 with default compiler to reproduce this crash.)
To solve this, we will first have to make it work on conan 2 as it's the default in Ubuntu 22

**Comment by ferdymercury** [comment]
It crashes still with latest master with Ubu 22.04. @php1ic does it crash also on your side? I just open A=12 and click on the second child.

**Comment by php1ic** [comment]
No crash for me, I can select any child in the A=12 tree, as well as all the grandchildren. This is with both a Debug and Release build. I'm on Fedora 39.

Do you get a core file, or can you run in gdb to get some debug details?

**Comment by ferdymercury** [comment]
Yes, the detail is here: https://github.com/martukas/nuclei/issues/8#issue-1746377566
It happens when an item is null.

**Comment by ferdymercury** [comment]
Here screenshot with QtCreator:

![image](https://github.com/martukas/nuclei/assets/10653970/91225a3f-2b3a-4956-9db6-d5f3126774a0)

**Comment by ferdymercury** [comment]
The following patch solves the crash:

![image](https://github.com/martukas/nuclei/assets/10653970/a4f8b001-7846-4a7c-b33e-063d3d66458f)

**Comment by ferdymercury** [comment]
`  L 4.44E3              2+`
 I guess this line is apparently missing here (invalid energy):
    
![image](https://github.com/martukas/nuclei/assets/10653970/bb81e1ed-55d5-46d6-ac3f-34650b914d03)

**Comment by ferdymercury** [comment]
Yeah, that line appears as PARSE MISMATCH in the logs, see attached.
[logs.txt](https://github.com/martukas/nuclei/files/14294011/logs.txt)

**Comment by ferdymercury** [comment]
@php1ic do you also get the same line as PARSE MISMATCH? If not, maybe our databases are different versions or sth like that?

**Comment by php1ic** [comment]
I get lots of `QGraphicsItemGroup::addToGroup: cannot add null item` lines when selecting that reaction channel for 12C but no parse mismatch lines.

I do get thousands of `HL parse mismatch` lines when the program starts up and a few `Invalid level`, but no crashes.

**Comment by ferdymercury** [comment]
> I get lots of `QGraphicsItemGroup::addToGroup: cannot add null item` lines when selecting that reaction channel for 12C but no parse mismatch lines.
> 
> I do get thousands of `HL parse mismatch` lines when the program starts up and a few `Invalid level`, but no crashes.

With https://github.com/martukas/nuclei/pull/25 the warnings and the crash disappear
